### ISSUE TITLE
Folder upload to codeocean data asset.

### ISSUE THREAD

**Issue by ZhixiaoSu** [AllenNeuralDynamics/ephys-sorting-manual-curation#22]
Issue: 
Since curation is organized by sessions and recording, we may end up with multiple curation files in each curation folder. (see [here](https://github.com/AllenNeuralDynamics/ephys-sorting-manual-curation/tree/main/behavior_717121_2024-06-15_10-00-58/experiment1_Record%20Node%20104%23Neuropix-PXI-100.ProbeA_recording1/kilosort2_5)) They can be from different users curating the same kilosort result or even from different results of kilosort pipeline (e.g. version with and without bad channel removal). 

And with current data asset upload rule, each curation asset will have all versions of curation.json (from different users, for different sorting results), making it hard to be used by a pipeline. (e.g. https://codeocean.allenneuraldynamics.org/capsule/1846086/tree) 

@alejoe91 and I talked about different ways to solve this issue. One would be to modify the data asset content. Will it be possible to not upload the not-modified old curation files when creating a new data asset for a new/modified curation? And will it be possible to also name the curation data asset with the suffix appened to curation file? For exmaple, 'curated-opto-ZhixiaoSu' instead of 'curated'?

**Comment by alejoe91** [comment]
Talked about it with David and Josh and they also agree on this. @jtyoung84 I'll make a PR to the upload script and we can discuss about it there

**Comment by alejoe91** [comment]
@jtyoung84 can we move on with the upload of the curation assets in the new format?

**Comment by jtyoung84** [comment]
Yep, sounds good. David approved the PR. I left a couple of small comments, but we can move forward with it.

**Comment by alejoe91** [comment]
Thanks! I'll address the comments tomorrow morning :)
